### PR TITLE
Remove install instructions from eOS, in favour of eOS-Doc

### PR DESCRIPTION
**Pull request by noahgibbs**
There's a corresponding PR in eOS-Doc to add them there.

### CODE REVIEW

**Comment by ChristopherA** [comment]
It is best to point to blank or .md, but not .html — Jekyll will do the right thing if link is md, but .using html does not view or edit correctly inside of GitHub. So we always link to md

**Comment by ChristopherA** [comment]
See my change to link in eos-doc repo README.md for example. It looks great in both GitHub and in web view.

**Comment by noahgibbs** [comment]
Sounds good. I'll fix this one, and fix various other places.

**Review by ChristopherA — APPROVED** [review]
ACK

**Pull request merged**
